apiVersion: apps/v1
kind: Deployment
metadata:
  name: online-shop-app
  labels:
    app: online-shop-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: online-shop-app
  template:
    metadata:
      labels:
        app: online-shop-app
    spec:
      containers:
      - name: online-shop-app
        image: trainwithshubham/online_shop_app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
